### PR TITLE
`o-image` performance

### LINKED ISSUE #801: O-image and o-gallery slow down the app.
### What is the current behavior?
When a big image, in my case 5MB, is loaded by this component it slows down all the app. Same behavior in o-gallery.

### Steps to reproduce
Just load a big image in one o-image and try to write in one o-text-input, the text should be shown with some lagg

### Affected versions:
- `ontimize-web-ngx`: 8.1.1

### Additional context
EDIT: I did some research and it seems that the component is calling the method getSrcValue so many times. If I remove the img previews on the lib it seems to work better.

### PR DESCRIPTION
**Pull request by manuel-cid**
Avoid calling `getSrcValue` on every change detection cycle in `o-image` component

fixes #801

### CODE REVIEW

File: projects/ontimize-web-ngx/src/lib/components/image/o-image.component.ts [hunk 1]
```diff
@@ -144,6 +129,8 @@ export class OImageComponent extends OFormDataComponent implements OnInit, OnDes
     } else {
       this.value = new OFormValue(undefined);
     }
+
+    this.src = this.getSrcValue();
```
Comment (daniel-grana) [inline projects/ontimize-web-ngx/src/lib/components/image/o-image.component.ts:133]: Pay attention, if val is instanceof OFormValue there is a return on line 118 and the value of src is not stored!

**Review by pacogomezimatia — APPROVED** [review]
